import Head from 'next/head'
import { useEffect, useMemo, useState } from 'react'
import styles from '../styles/Home.module.scss'

import { ref, child, get, update, orderByChild, query, equalTo } from "firebase/database";
import { database } from "./api/firebase";

import Header from '../components/Header';

export default function Home() {
  const [accountInfo, setAccountInfo] = useState({});
  const [loadedData, setLoadedData] = useState(0);
  const [logedIn, setLogedin] = useState(false);

  async function getData() {
    let accountdata = localStorage.getItem("accountInfo");
    if (!accountdata) accountdata = JSON.parse(sessionStorage.getItem("accountInfo"));
    if (!accountdata) return;
    await get(query(ref(database, "user"), orderByChild("nickname"), equalTo(accountdata.nickname)))
      .then((snapshot) => {
        if (snapshot.exists()) {
          const data = snapshot.val().filter(x => x);
          if (data[0].password === accountdata.password) {
            setLogedin(true);
            setAccountInfo({ ...data });
          }
        } else {
          console.log("Can't found data");
        };
      })
      .catch((error) => {
        console.error(error);
      });
  }

  useEffect(() => {
    getData();
  }, []);

  const header = useMemo(() => {
    return <Header logedIn={logedIn} />
  }, [logedIn])

  return (
    <>
      <Head>
        <title>Chess Army</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Luxurious+Roman&family=Saira+Condensed:wght@500&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.main}>
        {header}
      </main>
    </>
  )
}
