import Head from 'next/head'
import { useState } from 'react';
import styles from "../styles/Login.module.scss";
import Router, { useRouter } from 'next/router';

import { ref, child, get, update, orderByChild, query, equalTo } from "firebase/database";
import { database } from "./api/firebase";
const dbRef = ref(database);

export default function Home() {
    const [loginInfo, setLoginInfo] = useState({ "nickname": "", "password": "" });
    const [registerInfo, setRegisterInfo] = useState({ "nickname": "", "password": "", "re-password": "" });
    const [seePassword, setSeePassword] = useState(false);
    const router = useRouter();

    const handleSubmit = (e) => {
        e.preventDefault();
        console.log("NICKNAME:", loginInfo.nickname);
        console.log("PASSWORD:", loginInfo.password);

        get(query(ref(database, "user"), orderByChild("nickname"), equalTo(loginInfo.nickname)))
            .then((snapshot) => {
                if (snapshot.exists()) {
                    const data = snapshot.val().filter(x => x)[0];
                    if (data.password === loginInfo.password) {
                        localStorage.setItem("accountInfo", JSON.stringify({ "nickname": loginInfo.nickname, "password": loginInfo.password, "id": data.id + "" }));
                        router.push("/");
                    }
                } else {
                    console.log("Can't found data");
                };
            })
            .catch((error) => {
                console.error(error);
            });
    }

    return (
        <>
            <Head>
                <title>Chess Army</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <form onSubmit={handleSubmit}>
                    <h2><span>Đ</span><span>Ă</span><span>N</span><span>G</span> <span>N</span><span>H</span><span>Ậ</span><span>P</span></h2>
                    <div>
                        <input type="text" id="nickname" value={loginInfo.nickname} onChange={(e) => { setLoginInfo(prev => ({ ...prev, "nickname": e.target.value })) }}></input>
                        <label htmlFor="nickname">Tên tài khoản</label>
                    </div>
                    <div>
                        <input type={seePassword ? "text" : "password"} id="password" value={loginInfo.password} onChange={(e) => { setLoginInfo(prev => ({ ...prev, "password": e.target.value })) }}></input>
                        <label htmlFor="password">Mật khẩu</label>
                        {seePassword ? <i className="fa fa-eye" onClick={() => setSeePassword(false)}></i> : <i className="fa fa-eye-slash" onClick={() => setSeePassword(true)}></i>}
                    </div>
                    <input type="submit" name="submit" value="Đăng nhập"></input>
                </form>
            </main>
        </>
    )
}
